"""Evidence Classification for V0.2.1 Operational Qualification.

Every component in the research pipeline MUST declare its evidence class.
Reports MUST display evidence_class. Operational Qualification requires
HISTORICAL_REAL at minimum.

Prohibitions:
- A component CANNOT be labeled REAL/OPERATIONAL/VALIDATED/CONFIRMED/COMPLETE
  if evidence comes from: synthetic metrics, stub, mock, fixture, fake adapter,
  placeholder, or hardcoded result.

Evidence Classes:
- SYNTHETIC: Generated by code, not from real data
- FIXTURE: Test fixture, not operational data
- HISTORICAL_REAL: Real historical data from storage
- PAPER_REALTIME: Real-time paper trading data
- LIVE_REAL: Real live trading data (V0.3+)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class EvidenceClass(str, Enum):
    """Classification of evidence source quality.

    V0.2.1 §2: Reports must show evidence_class.
    V0.2.2 §9: Refined to distinguish fixture types.
    Operational Qualification requires HISTORICAL_MARKET_REAL.
    """

    SYNTHETIC = "SYNTHETIC"
    GENERATED_FIXTURE = "GENERATED_FIXTURE"  # Code-generated test data
    HISTORICAL_FIXTURE = "HISTORICAL_FIXTURE"  # Real capture saved as fixture
    HISTORICAL_MARKET_REAL = "HISTORICAL_MARKET_REAL"  # Real exchange OHLCV
    PAPER_REALTIME = "PAPER_REALTIME"
    LIVE_REAL = "LIVE_REAL"

    # Backward compatibility
    @property
    def is_operational(self) -> bool:
        """True if this evidence class qualifies for operational qualification.

        V0.2.2: HISTORICAL_MARKET_REAL required (not just HISTORICAL_REAL).
        """
        return self in (
            EvidenceClass.HISTORICAL_MARKET_REAL,
            EvidenceClass.PAPER_REALTIME,
            EvidenceClass.LIVE_REAL,
        )

    @property
    def label(self) -> str:
        """Human-readable label for reports."""
        return {
            EvidenceClass.SYNTHETIC: "SYNTHETIC (not operational)",
            EvidenceClass.GENERATED_FIXTURE: "GENERATED FIXTURE (test only)",
            EvidenceClass.HISTORICAL_FIXTURE: "HISTORICAL FIXTURE (real capture, test only)",
            EvidenceClass.HISTORICAL_MARKET_REAL: "HISTORICAL MARKET REAL DATA",
            EvidenceClass.PAPER_REALTIME: "PAPER REALTIME",
            EvidenceClass.LIVE_REAL: "LIVE REAL",
        }[self]


@dataclass(frozen=True, slots=True)
class EvidenceRecord:
    """Immutable record of evidence provenance for a component/result.

    Every BacktestResult, AuditResult, ValidationReport, etc. must carry
    an EvidenceRecord. The report claim validator checks these before
    allowing any component to be labeled REAL/OPERATIONAL/etc.
    """

    evidence_class: EvidenceClass
    source: str  # e.g., "OHLCVStore:data/storage/bot.db", "ListOHLCVSource:test"
    dataset_id: str = ""
    checksum: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not isinstance(self.evidence_class, EvidenceClass):
            raise TypeError(
                f"evidence_class must be EvidenceClass, got {type(self.evidence_class)}"
            )

    def assert_operational(self, component_name: str = "") -> None:
        """Raise if evidence is not operational quality.

        Use this before marking any component as REAL/OPERATIONAL.
        """
        if not self.evidence_class.is_operational:
            raise ValueError(
                f"{component_name}: evidence_class={self.evidence_class.value} "
                f"is not operational. Required: HISTORICAL_REAL or better. "
                f"Source: {self.source}"
            )

    def to_dict(self) -> dict[str, Any]:
        """Serialize for JSON output in reports."""
        return {
            "evidence_class": self.evidence_class.value,
            "source": self.source,
            "dataset_id": self.dataset_id,
            "checksum": self.checksum,
            "metadata": self.metadata,
        }


@dataclass(frozen=True, slots=True)
class ClaimValidation:
    """Result of validating a claim against evidence."""

    claim: str  # e.g., "REAL BACKTEST"
    valid: bool
    evidence_class: EvidenceClass
    reason: str = ""

    def __post_init__(self) -> None:
        pass


def validate_report_claims(
    claims: list[str],
    evidence: EvidenceRecord,
) -> list[ClaimValidation]:
    """Validate that report claims are supported by evidence.

    V0.2.1 §31: Report Claim Validator.
    If report contains "REAL BACKTEST", evidence must be HISTORICAL_REAL.
    If report contains "STRATEGY GENERATED", must have executable source.
    """
    results: list[ClaimValidation] = []
    for claim in claims:
        claim_upper = claim.upper()
        requires_real = any(
            kw in claim_upper
            for kw in ["REAL", "OPERATIONAL", "VALIDATED", "CONFIRMED", "COMPLETE"]
        )
        if requires_real:
            valid = evidence.evidence_class.is_operational
            results.append(
                ClaimValidation(
                    claim=claim,
                    valid=valid,
                    evidence_class=evidence.evidence_class,
                    reason="" if valid else f"Evidence class {evidence.evidence_class.value} insufficient for claim '{claim}'",
                )
            )
        else:
            results.append(
                ClaimValidation(
                    claim=claim,
                    valid=True,
                    evidence_class=evidence.evidence_class,
                )
            )
    return results


__all__ = [
    "ClaimValidation",
    "EvidenceClass",
    "EvidenceRecord",
    "validate_report_claims",
]
