"""Deterministic multi-agent foundation and communication runtime.

MA-0 provides neutral contracts and governance registries. MA-1 adds an
in-process communication plane, but neither phase has trading authority.
"""

from .blackboard import BLACKBOARD_TOPICS, Blackboard, BlackboardArtifact
from .bus import TOPIC_BY_MESSAGE_TYPE, AgentBus, MessageHandler
from .communication_errors import (
    CommunicationError,
    DuplicateMessageConflictError,
    EvidenceMissingError,
    ExpiredMessageError,
    InvalidMessageError,
    ReplyCorrelationError,
    SessionMaxRoundsError,
    SessionTerminatedError,
    SessionTimeoutError,
    TraceMismatchError,
    UnauthorizedTopicError,
    UnknownReceiverError,
    UnknownSenderError,
)
from .contracts import (
    AgentCapability,
    AgentEvidence,
    AgentLifecycleState,
    AgentManifest,
    AgentMessage,
    AgentMessageType,
    AgentRole,
    DeclaredCapabilities,
    ForbiddenAction,
    TraceContext,
    TradeDirection,
    TradeProposal,
    TradeProposalStatus,
    VerificationMetadata,
)
from .registry import (
    AgentRegistry,
    CapabilityDeniedError,
    CapabilityPolicy,
    CapabilityRegistry,
    DuplicateAgentVersionError,
    InvalidLifecycleTransitionError,
    MultiAgentGovernanceError,
    UnknownAgentError,
)
from .session import (
    CommunicationReplay,
    CommunicationSession,
    CommunicationSessionState,
    SessionStatus,
)

__all__ = [
    "BLACKBOARD_TOPICS",
    "TOPIC_BY_MESSAGE_TYPE",
    "AgentBus",
    "AgentCapability",
    "AgentEvidence",
    "AgentLifecycleState",
    "AgentManifest",
    "AgentMessage",
    "AgentMessageType",
    "AgentRegistry",
    "AgentRole",
    "Blackboard",
    "BlackboardArtifact",
    "CapabilityDeniedError",
    "CapabilityPolicy",
    "CapabilityRegistry",
    "CommunicationError",
    "CommunicationReplay",
    "CommunicationSession",
    "CommunicationSessionState",
    "DeclaredCapabilities",
    "DuplicateAgentVersionError",
    "DuplicateMessageConflictError",
    "EvidenceMissingError",
    "ExpiredMessageError",
    "ForbiddenAction",
    "InvalidLifecycleTransitionError",
    "InvalidMessageError",
    "MessageHandler",
    "MultiAgentGovernanceError",
    "ReplyCorrelationError",
    "SessionMaxRoundsError",
    "SessionStatus",
    "SessionTerminatedError",
    "SessionTimeoutError",
    "TraceContext",
    "TraceMismatchError",
    "TradeDirection",
    "TradeProposal",
    "TradeProposalStatus",
    "UnauthorizedTopicError",
    "UnknownAgentError",
    "UnknownReceiverError",
    "UnknownSenderError",
    "VerificationMetadata",
]
