"""Deterministic direction arbitration for simultaneous LONG/SHORT alternatives.

Contract (ADR-DIR-0001, checkpoint MA-DIRECTION-ARBITRATION-AND-POC02-REPAIR-01):

Simultaneous LONG/SHORT ``TradeProposal`` artifacts generated by ONE
directional evaluation (same strategy family, asset, timeframe, decision
window) are ``ALTERNATIVE_DIRECTIONS`` — the two mutually exclusive sides of a
single hypothesis — not independent claims. They are grouped into an immutable
``OpportunityGroup`` and resolved by a deterministic, LLM-free
``DirectionArbiter`` BEFORE multi-agent critique:

    Strategy Evaluation → Directional Candidates → OpportunityGroup
        → direction arbitration / ranking
        → one direction OR explicit NONE (NO_TRADE)
        → TradeProposal → multi-agent critique

Design constraints committed here:

* Deterministic authority (DIR-05 / D2): selection uses ONLY scores already
  produced by strategy logic and evidence quality (the MA-4 ``MetaRanker``
  components over strategy-generated evidence). There is no LLM anywhere in
  this module; critics may critique the selected hypothesis and surface
  counter-evidence but can never fabricate a directional signal.
* ``NONE`` is first-class (DIR-06 / E1): an unresolved score tie, a missing
  side, or a score below the preregistered floor yields
  ``selected_direction="NONE"`` — the group contributes no proposal to
  critique and the decision layer sees NO_TRADE. ``NO_FORCED_DIRECTION`` is a
  structural property: nothing in this module can manufacture a direction.
* Conflict semantics (DIR-04 / D3): arbitration is scope-limited to groups
  within one (asset, strategy, timeframe, decision window). The losing side of
  a resolved group is recorded as ``EXPECTED_ALTERNATIVE_DIRECTION`` — its
  existence and evidence are preserved in the group provenance, never
  stripped. Cross-strategy opposition is NEVER arbitrated: it stays a genuine
  conflict for the CounterSignalCritic (``TRUE_COUNTER_EVIDENCE``), whose
  contract and authority are unchanged (DIR-07).
* Fail-closed (mirror of MA-2/MA-4 authority rules): foreign-run candidates,
  future-dated proposals or evidence, and unregistered evidence are rejected,
  never silently dropped.
* Replay-deterministic (DIR-10): identical inputs produce a byte-identical
  group (hash-derived ``group_id``), verified independently by
  ``OpportunityGroupVerifier`` (DIR-08 builder != verifier).
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum
from hashlib import sha256
from typing import Any, Final

from trading_bot.multi_agent.contracts import TradeDirection, TradeProposal
from trading_bot.multi_agent.opportunity import MetaRanker, Opportunity

ARBITRATION_SCHEMA_VERSION: Final[str] = "dir-v1"
ARBITER_ID: Final[str] = "direction-arbiter"
GROUP_VERIFIER_ID: Final[str] = "opportunity-group-verifier"
ARBITER_VERSION: Final[str] = "direction-arbiter-v1"
GROUP_VERIFIER_VERSION: Final[str] = "opportunity-group-verifier-v1"

SELECTED_LONG: Final[str] = "LONG"
SELECTED_SHORT: Final[str] = "SHORT"
SELECTED_NONE: Final[str] = "NONE"

# Preregistered selection reasons (closed set — no free-form authority).
REASON_HIGHER_SCORE: Final[str] = "HIGHER_EVIDENCE_SCORE"
REASON_SCORE_TIE: Final[str] = "UNRESOLVED_SCORE_TIE"
REASON_SOLE_CANDIDATE: Final[str] = "SOLE_DIRECTIONAL_CANDIDATE"
REASON_BELOW_FLOOR: Final[str] = "BELOW_MIN_DIRECTION_SCORE"
REASON_ALTERNATIVE: Final[str] = "EXPECTED_ALTERNATIVE_DIRECTION"


class ArbitrationError(ValueError):
    """Raised when a group cannot be formed or resolved fail-closed."""


class GroupVerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


def _canonical_hash(payload: object) -> str:
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str).encode()
    return sha256(encoded).hexdigest()


@dataclass(frozen=True, slots=True)
class DirectionScore:
    """Immutable arbitration score for one side of a group."""

    direction: str
    proposal_ref: str
    score: float
    score_components: tuple[tuple[str, float], ...]
    evidence_refs: tuple[str, ...]

    def to_dict(self) -> dict[str, Any]:
        return {
            "direction": self.direction,
            "proposal_ref": self.proposal_ref,
            "score": self.score,
            "score_components": [list(item) for item in self.score_components],
            "evidence_refs": list(self.evidence_refs),
        }


@dataclass(frozen=True, slots=True)
class OpportunityGroup:
    """Immutable provenance record for one directional evaluation.

    Both candidate refs survive arbitration regardless of the outcome: the
    losing direction is never stripped from provenance (DIR-08/G).
    """

    schema_version: str
    group_id: str
    run_id: str
    trace_id: str
    asset: str
    strategy: str
    timeframe: str
    decision_time: datetime
    long_candidate_ref: str | None
    short_candidate_ref: str | None
    direction_scores: tuple[DirectionScore, ...]
    selected_direction: str
    selection_reason: str
    counter_evidence: tuple[str, ...]
    confidence: float
    created_at: datetime

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "group_id": self.group_id,
            "run_id": self.run_id,
            "trace_id": self.trace_id,
            "asset": self.asset,
            "strategy": self.strategy,
            "timeframe": self.timeframe,
            "decision_time": self.decision_time.isoformat(),
            "long_candidate_ref": self.long_candidate_ref,
            "short_candidate_ref": self.short_candidate_ref,
            "direction_scores": [item.to_dict() for item in self.direction_scores],
            "selected_direction": self.selected_direction,
            "selection_reason": self.selection_reason,
            "counter_evidence": list(self.counter_evidence),
            "confidence": self.confidence,
            "created_at": self.created_at.isoformat(),
        }


def _group_id(payload: Mapping[str, Any]) -> str:
    return "group:" + _canonical_hash(payload)[:24]


class DirectionArbiter:
    """Deterministic, LLM-free arbitration over one directional evaluation."""

    version = ARBITER_VERSION

    def __init__(self, *, min_direction_score: float = 0.0) -> None:
        # Preregistered default 0.0 = no additional gate: signal thresholds
        # stay owned by the strategy families (unchanged). The floor exists so
        # the composition MAY freeze a stricter contract in a manifest.
        if min_direction_score < 0.0:
            raise ArbitrationError("min_direction_score must be non-negative")
        self.min_direction_score = min_direction_score

    # -- group formation ----------------------------------------------------

    def form_groups(
        self,
        *,
        run_id: str,
        trace_id: str,
        proposals: Mapping[str, TradeProposal],
        evidence_registry: Mapping[str, Any],
        assessments: Mapping[str, Any] | None = None,
        decision_time: datetime | None = None,
        source_agent_id_by_ref: Mapping[str, str] | None = None,
    ) -> tuple[OpportunityGroup, ...]:
        """Partition admissible proposals into per-evaluation groups.

        Groups are keyed by (asset, strategy, timeframe, data_time): exactly
        the identity of one directional evaluation. Cross-strategy or
        cross-asset opposition is deliberately NOT grouped.
        """
        if decision_time is not None and decision_time.tzinfo is None:
            raise ArbitrationError("decision_time must be timezone-aware")
        for proposal in proposals.values():
            self._validate_candidate(proposal, run_id=run_id, decision_time=decision_time)
            for ref in proposal.evidence_refs:
                evidence = evidence_registry.get(ref)
                if evidence is None:
                    raise ArbitrationError(f"candidate evidence not registered: {ref}")
                if getattr(evidence, "run_id", None) != run_id:
                    raise ArbitrationError(f"evidence run does not match group run: {ref}")

        partitions: dict[tuple[str, str, str, str], list[TradeProposal]] = {}
        for proposal_id in sorted(proposals):
            proposal = proposals[proposal_id]
            if proposal.direction is TradeDirection.NO_TRADE:
                continue  # NO_TRADE never becomes an opportunity (MA-2 rule)
            key = (
                proposal.asset,
                proposal.strategy,
                proposal.timeframe,
                proposal.data_time.isoformat(),
            )
            partitions.setdefault(key, []).append(proposal)

        groups: list[OpportunityGroup] = []
        for key in sorted(partitions):
            members = partitions[key]
            longs = [item for item in members if item.direction is TradeDirection.LONG]
            shorts = [item for item in members if item.direction is TradeDirection.SHORT]
            if len(longs) > 1 or len(shorts) > 1:
                raise ArbitrationError(
                    f"ambiguous directional evaluation {key}: "
                    f"{len(longs)} LONG / {len(shorts)} SHORT candidates"
                )
            groups.append(
                self._build_group(
                    run_id=run_id,
                    trace_id=trace_id,
                    long_proposal=longs[0] if longs else None,
                    short_proposal=shorts[0] if shorts else None,
                    evidence_registry=evidence_registry,
                    assessment=(assessments or {}).get(key[0]),
                    decision_time=decision_time,
                    source_agent_id_by_ref=source_agent_id_by_ref,
                )
            )
        return tuple(groups)

    # -- selection ----------------------------------------------------------

    def select_direction(
        self,
        group: OpportunityGroup,
        *,
        proposals: Mapping[str, TradeProposal],
    ) -> OpportunityGroup:
        """Apply the deterministic selection rule to a formed group.

        Rule (closed set): sole candidate → select it; both sides present →
        strictly higher arbitration score wins; tie or below-floor score →
        NONE. There is no code path that can invent a direction.
        """
        scores = {item.direction: item for item in group.direction_scores}
        if group.selected_direction != SELECTED_NONE or group.selection_reason != "":
            raise ArbitrationError("group already resolved")
        long_ref = group.long_candidate_ref
        short_ref = group.short_candidate_ref
        if long_ref is None and short_ref is None:
            return group  # empty group stays NONE with empty reason
        if long_ref is not None and short_ref is None:
            if self._below_floor(group, SELECTED_LONG):
                return self._resolved(
                    group, proposals, selected=SELECTED_NONE, reason=REASON_BELOW_FLOOR
                )
            return self._resolved(
                group, proposals, selected=SELECTED_LONG, reason=REASON_SOLE_CANDIDATE
            )
        if short_ref is not None and long_ref is None:
            if self._below_floor(group, SELECTED_SHORT):
                return self._resolved(
                    group, proposals, selected=SELECTED_NONE, reason=REASON_BELOW_FLOOR
                )
            return self._resolved(
                group, proposals, selected=SELECTED_SHORT, reason=REASON_SOLE_CANDIDATE
            )
        long_score = scores[SELECTED_LONG].score
        short_score = scores[SELECTED_SHORT].score
        if long_score < self.min_direction_score and short_score < self.min_direction_score:
            return self._resolved(group, proposals, selected=SELECTED_NONE, reason=REASON_BELOW_FLOOR)
        if long_score == short_score:
            return self._resolved(group, proposals, selected=SELECTED_NONE, reason=REASON_SCORE_TIE)
        winner = SELECTED_LONG if long_score > short_score else SELECTED_SHORT
        return self._resolved(group, proposals, selected=winner, reason=REASON_HIGHER_SCORE)

    # -- internals ----------------------------------------------------------

    def _below_floor(self, group: OpportunityGroup, direction: str) -> bool:
        score = next(
            (item.score for item in group.direction_scores if item.direction == direction),
            None,
        )
        return score is None or score < self.min_direction_score

    def _resolved(
        self,
        group: OpportunityGroup,
        proposals: Mapping[str, TradeProposal],
        *,
        selected: str,
        reason: str,
    ) -> OpportunityGroup:
        losing_ref = (
            group.short_candidate_ref
            if selected == SELECTED_LONG
            else group.long_candidate_ref
        )
        counter: tuple[str, ...] = ()
        if losing_ref is not None:
            loser = proposals.get(losing_ref)
            counter = tuple(sorted(loser.evidence_refs)) if loser is not None else ()
        winner_score = next(
            (
                item.score
                for item in group.direction_scores
                if item.direction == selected
            ),
            0.0,
        )
        updated = OpportunityGroup(
            schema_version=group.schema_version,
            group_id=group.group_id,
            run_id=group.run_id,
            trace_id=group.trace_id,
            asset=group.asset,
            strategy=group.strategy,
            timeframe=group.timeframe,
            decision_time=group.decision_time,
            long_candidate_ref=group.long_candidate_ref,
            short_candidate_ref=group.short_candidate_ref,
            direction_scores=group.direction_scores,
            selected_direction=selected,
            selection_reason=reason,
            counter_evidence=counter,
            confidence=round(winner_score, 6) if selected != SELECTED_NONE else 0.0,
            created_at=group.created_at,
        )
        return updated

    def _build_group(
        self,
        *,
        run_id: str,
        trace_id: str,
        long_proposal: TradeProposal | None,
        short_proposal: TradeProposal | None,
        evidence_registry: Mapping[str, Any],
        assessment: Any | None,
        decision_time: datetime | None,
        source_agent_id_by_ref: Mapping[str, str] | None,
    ) -> OpportunityGroup:
        scores: list[DirectionScore] = []
        for _direction, proposal in (
            (SELECTED_LONG, long_proposal),
            (SELECTED_SHORT, short_proposal),
        ):
            if proposal is None:
                continue
            scores.append(
                self._score(proposal, evidence_registry, assessment, source_agent_id_by_ref)
            )
        decision_time = decision_time or max(
            (item.data_time for item in (long_proposal, short_proposal) if item is not None),
            default=datetime.fromtimestamp(0, tz=UTC),
        )
        identity = {
            "run_id": run_id,
            "asset": long_proposal.asset if long_proposal else short_proposal.asset if short_proposal else None,
            "strategy": long_proposal.strategy if long_proposal else short_proposal.strategy if short_proposal else None,
            "timeframe": long_proposal.timeframe if long_proposal else short_proposal.timeframe if short_proposal else None,
            "decision_time": decision_time.isoformat(),
            "long_ref": long_proposal.proposal_id if long_proposal else None,
            "short_ref": short_proposal.proposal_id if short_proposal else None,
            "min_direction_score": self.min_direction_score,
        }
        return OpportunityGroup(
            schema_version=ARBITRATION_SCHEMA_VERSION,
            group_id=_group_id(identity),
            run_id=run_id,
            trace_id=trace_id,
            asset=str(identity["asset"]),
            strategy=str(identity["strategy"]),
            timeframe=str(identity["timeframe"]),
            decision_time=decision_time,
            long_candidate_ref=long_proposal.proposal_id if long_proposal else None,
            short_candidate_ref=short_proposal.proposal_id if short_proposal else None,
            direction_scores=tuple(sorted(scores, key=lambda item: item.direction)),
            selected_direction=SELECTED_NONE,
            selection_reason="",
            counter_evidence=(),
            confidence=0.0,
            created_at=decision_time,
        )

    def _score(
        self,
        proposal: TradeProposal,
        evidence_registry: Mapping[str, Any],
        assessment: Any | None,
        source_agent_id_by_ref: Mapping[str, str] | None,
    ) -> DirectionScore:
        """Score one side with the MA-4 MetaRanker over strategy evidence."""
        evidence = evidence_registry.get(proposal.evidence_refs[0]) if proposal.evidence_refs else None
        source_agent_id = (
            (source_agent_id_by_ref or {}).get(proposal.proposal_id)
            or getattr(evidence, "producer_agent_id", None)
            or "unknown"
        )
        scored = MetaRanker().score(
            Opportunity(
                proposal=proposal,
                evidence_refs=tuple(proposal.evidence_refs),
                source_agent_id=str(source_agent_id),
                source_agent_version="1",
            ),
            assessment=assessment,
            conflicted=False,  # arbitration precedes board conflicts by design
        )
        return DirectionScore(
            direction=proposal.direction.value,
            proposal_ref=proposal.proposal_id,
            score=scored.score,
            score_components=scored.score_components,
            evidence_refs=tuple(sorted(proposal.evidence_refs)),
        )

    def _validate_candidate(
        self, proposal: TradeProposal, *, run_id: str, decision_time: datetime | None
    ) -> None:
        if proposal.run_id != run_id:
            raise ArbitrationError("candidate run does not match group run")
        if proposal.direction not in (TradeDirection.LONG, TradeDirection.SHORT):
            raise ArbitrationError(
                f"candidate direction not arbitable: {proposal.direction.value}"
            )
        if not proposal.evidence_refs:
            raise ArbitrationError("candidate requires evidence")
        if proposal.data_time > proposal.created_at:
            raise ArbitrationError("future-dated candidate data is not admissible")
        if decision_time is not None and proposal.data_time > decision_time:
            raise ArbitrationError("candidate data is future-dated versus decision time")


# ---------------------------------------------------------------------------
# TRACK G — independent verifier (builder != verifier)
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class GroupVerification:
    """Immutable result of independent OpportunityGroup verification."""

    group_id: str
    verdict: GroupVerificationStatus
    checks: tuple[tuple[str, str, str], ...]

    @property
    def passed(self) -> bool:
        return self.verdict is GroupVerificationStatus.VERIFIED

    def to_dict(self) -> dict[str, Any]:
        return {
            "group_id": self.group_id,
            "verdict": self.verdict.value,
            "checks": [[name, status, detail] for name, status, detail in self.checks],
        }


class OpportunityGroupVerifier:
    """Independent deterministic verification of an OpportunityGroup.

    Not the arbiter: this class re-derives every claim from the authoritative
    proposals/evidence and compares. A forged score, a stripped losing side,
    a foreign-run candidate, or future-dated evidence fails verification.
    """

    version = GROUP_VERIFIER_VERSION

    def __init__(self, *, min_direction_score: float = 0.0) -> None:
        self.min_direction_score = min_direction_score

    def verify(
        self,
        group: OpportunityGroup,
        *,
        proposals: Mapping[str, TradeProposal],
        evidence_registry: Mapping[str, Any],
        assessments: Mapping[str, Any] | None = None,
        now: datetime | None = None,
    ) -> GroupVerification:
        checks: list[tuple[str, str, str]] = []

        def record(name: str, ok: bool, detail: str = "") -> None:
            checks.append((name, "PASS" if ok else "FAIL", detail))

        arbiter = DirectionArbiter(min_direction_score=self.min_direction_score)

        # Run authority.
        refs = [ref for ref in (group.long_candidate_ref, group.short_candidate_ref) if ref]
        foreign = sorted(
            ref for ref in refs if ref not in proposals or proposals[ref].run_id != group.run_id
        )
        record("run_authority_candidates", not foreign, f"foreign={foreign}")

        # Candidate binding: refs resolve and match group identity.
        binding_bad: list[str] = []
        for ref in refs:
            proposal = proposals.get(ref)
            if proposal is None:
                binding_bad.append(f"{ref}:missing")
                continue
            if (
                proposal.asset != group.asset
                or proposal.strategy != group.strategy
                or proposal.timeframe != group.timeframe
                or proposal.trace_id != group.trace_id
            ):
                binding_bad.append(f"{ref}:identity-mismatch")
            if proposal.direction.value != (
                SELECTED_LONG if ref == group.long_candidate_ref else SELECTED_SHORT
            ):
                binding_bad.append(f"{ref}:direction-mismatch")
        record("candidate_binding", not binding_bad, f"violations={binding_bad}")

        # No stripping: both sides that existed must still be recorded.
        present_long = any(
            item.direction == SELECTED_LONG for item in group.direction_scores
        )
        present_short = any(
            item.direction == SELECTED_SHORT for item in group.direction_scores
        )
        stripping = (
            (group.long_candidate_ref is not None and not present_long)
            or (group.short_candidate_ref is not None and not present_short)
            or (group.long_candidate_ref is None and present_long)
            or (group.short_candidate_ref is None and present_short)
        )
        record(
            "losing_direction_preserved",
            not stripping,
            f"long={group.long_candidate_ref} short={group.short_candidate_ref}",
        )

        # Direction score integrity: re-derive with the same deterministic rule.
        score_bad: list[str] = []
        for recorded in group.direction_scores:
            proposal = proposals.get(recorded.proposal_ref)
            if proposal is None:
                score_bad.append(f"{recorded.proposal_ref}:missing")
                continue
            assessment = (assessments or {}).get(proposal.asset)
            rederived = arbiter._score(proposal, evidence_registry, assessment, None)
            if (
                rederived.score != recorded.score
                or rederived.score_components != recorded.score_components
                or rederived.evidence_refs != recorded.evidence_refs
            ):
                score_bad.append(f"{recorded.proposal_ref}:score-mismatch")
        record("direction_score_integrity", not score_bad, f"violations={score_bad}")

        # Selection integrity: re-apply the closed-set rule.
        resolved = arbiter.select_direction(
            OpportunityGroup(
                schema_version=group.schema_version,
                group_id=group.group_id,
                run_id=group.run_id,
                trace_id=group.trace_id,
                asset=group.asset,
                strategy=group.strategy,
                timeframe=group.timeframe,
                decision_time=group.decision_time,
                long_candidate_ref=group.long_candidate_ref,
                short_candidate_ref=group.short_candidate_ref,
                direction_scores=group.direction_scores,
                selected_direction=SELECTED_NONE,
                selection_reason="",
                counter_evidence=(),
                confidence=0.0,
                created_at=group.created_at,
            ),
            proposals=proposals,
        )
        selection_ok = (
            resolved.selected_direction == group.selected_direction
            and resolved.selection_reason == group.selection_reason
            and resolved.counter_evidence == group.counter_evidence
        )
        record(
            "selection_integrity",
            selection_ok,
            f"expected={resolved.selected_direction}/{resolved.selection_reason} "
            f"recorded={group.selected_direction}/{group.selection_reason}",
        )

        # Counter-evidence integrity: recorded refs must belong to the losing
        # side (EXPECTED_ALTERNATIVE_DIRECTION), never to fabricated sources.
        losing_ref = (
            group.short_candidate_ref
            if group.selected_direction == SELECTED_LONG
            else group.long_candidate_ref
        )
        expected_counter: tuple[str, ...] = ()
        if group.selected_direction != SELECTED_NONE and losing_ref is not None:
            loser = proposals.get(losing_ref)
            if loser is not None:
                expected_counter = tuple(sorted(loser.evidence_refs))
        counter_ok = (
            group.selected_direction == SELECTED_NONE
            or group.counter_evidence == expected_counter
        )
        record(
            "counter_evidence_integrity",
            counter_ok,
            f"expected={expected_counter} recorded={group.counter_evidence}",
        )

        # PIT: proposal data and bound evidence must predate decision time.
        pit_bad: list[str] = []
        for ref in refs:
            proposal = proposals.get(ref)
            if proposal is None:
                continue
            if proposal.data_time > group.decision_time:
                pit_bad.append(f"{ref}:future-proposal")
            for evidence_ref in proposal.evidence_refs:
                evidence = evidence_registry.get(evidence_ref)
                if evidence is None:
                    pit_bad.append(f"{evidence_ref}:unregistered")
                elif getattr(evidence, "available_at", None) is not None and (
                    evidence.available_at > group.decision_time
                ):
                    pit_bad.append(f"{evidence_ref}:future-evidence")
        record("pit_binding", not pit_bad, f"violations={pit_bad}")

        # Replay determinism: group id re-derivation must match (DIR-10).
        replay_id = _group_id(
            {
                "run_id": group.run_id,
                "asset": group.asset,
                "strategy": group.strategy,
                "timeframe": group.timeframe,
                "decision_time": group.decision_time.isoformat(),
                "long_ref": group.long_candidate_ref,
                "short_ref": group.short_candidate_ref,
                "min_direction_score": self.min_direction_score,
            }
        )
        record("group_id_deterministic", replay_id == group.group_id, f"recomputed={replay_id}")

        verdict = (
            GroupVerificationStatus.VERIFIED
            if all(status == "PASS" for _, status, _ in checks)
            else GroupVerificationStatus.REJECTED
        )
        return GroupVerification(
            group_id=group.group_id,
            verdict=verdict,
            checks=tuple(checks),
        )


__all__ = [
    "ARBITER_ID",
    "ARBITRATION_SCHEMA_VERSION",
    "GROUP_VERIFIER_ID",
    "REASON_ALTERNATIVE",
    "REASON_BELOW_FLOOR",
    "REASON_HIGHER_SCORE",
    "REASON_SCORE_TIE",
    "REASON_SOLE_CANDIDATE",
    "SELECTED_LONG",
    "SELECTED_NONE",
    "SELECTED_SHORT",
    "ArbitrationError",
    "DirectionArbiter",
    "DirectionScore",
    "GroupVerification",
    "GroupVerificationStatus",
    "OpportunityGroup",
    "OpportunityGroupVerifier",
]
